export const strings = {
  Login_tit: "Let's Login you in.",
  Login_disc: "Welcome back\nYou've been missed!",
  U_E_placeholder: 'Username or Email',
  password: 'Password',
  forgotPassword: 'Forgot password?',
  dont_acc: "Don't have an account ?",
  ragister: 'Register',
  SignIn: 'SignIn',
  FirstName: 'First Name',
  LastName: 'Last Name',
  Email: 'Email',
  Phone: 'Phone',
  SignUp: 'SignUp',
  Re_Password: 'Re-Password',
  Add_post: 'Add Post',
  No_image: 'No Images at the moment !',
  title: 'Title',
  description: 'Description',
  post: 'Post',
  like: 'Like',
};
